micronaut:
  server:
    port: 8131
  application:
    name: aglAuthenticationService
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
netty:
  default:
    allocator:
      max-order: 3


datasources:
  default:
    url: ${PG_JDBC_URL:`jdbc:postgresql://localhost:5432/users`}
    username: ${PG_USERNAME:postgres}
    password: ${PG_PASSWORD:AstonVilla!96}
    driver-class-name: org.postgresql.Driver
    schema-generate: NONE
    dialect: POSTGRES


flyway:
  datasources:
    default:
      locations: classpath:/db/migration
      baseline-on-migrate: false
      validate-on-migrate: true